### ISSUE TITLE
Add a page navigation to the site header

### ISSUE THREAD

**Issue by davidstanke** [r9y-dev/site#12]
Allow navigation between pages:
- home
- discuss
- (???)

**Comment by davidstanke** [comment]
☹️ I couldn't figure out how do make a navigation menu. I tried various solutions I found on the web but none of them made the nav appear. (AFAICT, the theme itself should generate the nav, if the appropriate metadata is found. But it doesn't appear for me.)

**Comment by stevemcghee** [comment]
@proffalken any ideas?

**Comment by proffalken** [comment]
@stevemcghee see above PR - there's a file missing.

![image](https://user-images.githubusercontent.com/262545/201414339-9f7d97c2-b961-4b67-9343-48064fecd504.png)

We probably want to look at the formatting of that, and why it starts on the far-right rather than the left of the banner, but we can at least get the nav section up there for now.
